modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="acmodpack"
version="1.0.0"
displayName="AC-modpack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="chris, MCreator"

[[dependencies.acmodpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




